### ISSUE TITLE
Make paramnames unique for trap density / lifetime

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoCTI#15]
The module.results file paramnames look as follows:

parallel_ccd_well_notch_depth                               3.775 (-2.994, 15.083)
parallel_ccd_well_fill_beta                                 0.58 (0.576, 0.583)
parallel_species_trap_density                               0.139 (0.217, 0.265)
parallel_species_trap_density                               0.242 (0.217, 0.265)
parallel_species_trap_lifetime                              1.285 (4.193, 4.96)
parallel_species_trap_lifetime                              4.552 (4.193, 4.96)

We need to make it so that trap_density / trap_lifetime are unique for every species (e.g. add an integer index). This will fix the errors, which are duplicated.

**Comment by rhayes777** [comment]
ListPriorModels now add the index of the contained prior model to the prior name when generating param names
