### ISSUE TITLE
Error on import with latest released version

### ISSUE THREAD

**Issue by mwcraig** [Jammy2211/PyAutoCTI#53]
As part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4904) I tried installing `autocti`. 

Though there were no errors during installation, I got an error in `welcome.py` which I can reproduce by simply doing `import autocti as ac`:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattcraig/mambaforge/envs/pyautoci/lib/python3.10/site-packages/autocti/__init__.py", line 10, in <module>
    from arcticpy import ROE
  File "/Users/mattcraig/mambaforge/envs/pyautoci/lib/python3.10/site-packages/arcticpy/__init__.py", line 1, in <module>
    from arcticpy.cti import add_cti, remove_cti, CTI_model_for_HST_ACS
  File "/Users/mattcraig/mambaforge/envs/pyautoci/lib/python3.10/site-packages/arcticpy/cti.py", line 8, in <module>
    from arcticpy.ccd import CCDPhase, CCD
  File "/Users/mattcraig/mambaforge/envs/pyautoci/lib/python3.10/site-packages/arcticpy/ccd.py", line 3, in <module>
    from autoconf.dictable import Dictable
ImportError: cannot import name 'Dictable' from 'autoconf.dictable' (/Users/mattcraig/mambaforge/envs/pyautoci/lib/python3.10/site-packages/autoconf/dictable.py)
```

## my installation steps

```bash
mamba create -n pyautoci python=3.10 scipy=1.8
conda activate pyautoci
pip install autocti
pip install arcticpy_no_gsl
```

**Comment by rhayes777** [comment]
Apologies I think this is due to changes to the API in a library. I've pushed a fix although @Jammy2211 will have to advise when that will be released.

**Comment by rhayes777** [comment]
@Jammy2211 

Looks like arcticpy also needs updating:

`ImportError while loading conftest '/home/runner/work/PyAutoCTI/PyAutoCTI/PyAutoCTI/test_autocti/conftest.py'.
test_autocti/conftest.py:6: in <module>
    import autocti as ac
autocti/__init__.py:10: in <module>
    from arcticpy import ROE
/opt/hostedtoolcache/Python/3.9.[18](https://github.com/Jammy2211/PyAutoCTI/actions/runs/6529920316/job/17728316475#step:10:19)/x64/lib/python3.9/site-packages/arcticpy/__init__.py:1: in <module>
    from arcticpy.cti import add_cti, remove_cti, CTI_model_for_HST_ACS
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/arcticpy/cti.py:8: in <module>
    from arcticpy.ccd import CCDPhase, CCD
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/arcticpy/ccd.py:3: in <module>
    from autoconf.dictable import Dictable
E   ImportError: cannot import name 'Dictable' from 'autoconf.dictable' (/home/runner/work/PyAutoCTI/PyAutoCTI/PyAutoConf/autoconf/dictable.py)`

**Comment by Jammy2211** [comment]
Just to add, I am implementing Python3.11 support this week :).

**Comment by mwcraig** [comment]
> Just to add, I am implementing Python3.11 support this week :).

Wonderful! Let me know when it is ready to tes...

**Comment by Jammy2211** [comment]
`pip install arcticpy_no_gsl==2.5` should fix the issue.

**Comment by mwcraig** [comment]
Thanks, that did the trick -- I'll get back to the rest of the review on Monday.
