### ISSUE TITLE
Suggestions for welcome.py script

### ISSUE THREAD

**Issue by mwcraig** [Jammy2211/PyAutoCTI#69]
I really like the `welcome.py` script! A couple of minor suggestions for it:

1. Add a prompt that you need to close the matplotlib window for the script to complete.
2. The numba warning ends with a line that starts "Install numba as described at the following webpage..." but there is no following web page.

**Comment by Jammy2211** [comment]
The welcome.py message has been updated:

https://github.com/Jammy2211/autocti_workspace/blob/main/welcome.py

```
    NOTE: If a matplotlib figure window appears, you may need to close it via the X button and then press 
    enter to continue the script.
```

I have updated the exception on numba to point to this webpage: https://pyautolens.readthedocs.io/en/latest/installation/numba.html

Thank you!
