### ISSUE TITLE
Integration test running - Things to change

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoCTI#7]
The parallel one species integration test is running!

However, to do this, I had to 'hack' the ci data extraction in phase.py specifically lines 139-149 in the make_analysis function. I couldn't get the mask (which is not part of CIData) to use the extraction routines in CIData. So, I hacked this extraction 'by-hand'.

The first thing you should do is make it so the mask uses the same function as the data :).

**Comment by Jammy2211** [comment]
This extract of text now addeds two masks if the image has two images, as I have an added an integration test that checks pooling works.

**Comment by rhayes777** [comment]
I've generalised mask adding. Seems to work as the integration and unit tests pass.
